services:
  dbMysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toDoDatabase
    volumes:
      - todo-data:/var/lib/mysql

  webphp:
    depends_on: 
      - dbMysql
    build: .
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      
      

volumes:
  todo-data: